---
format:
  html:
    embed-resources: false
    toc: true
    toc-depth: 3

execute:
  cache: false
  echo: false
  warnings: false
  error: false

---

```{r}
#| results: "asis"
#| echo: false
#| warning: false
#| message: false
source("../../_common.R")
status(type = "polishing")
```

::: {.callout-note appearance="simple" collapse="false" #infoc-svarmpat}

## [In-focus]{.in-focus} - SvarmPat {.unnumbered}

### SvarmPat – monitoring of resistance in pathogens from farm animals


The SvarmPat programme (Swedish Veterinary Antibiotic Resistance Monitoring – farm animal pathogens) is a project in cooperation between Farm & Animal Health and SVA that started in 2005. It is financed by the Swedish Board of Agriculture.  

The purpose of SvarmPat is to reduce emergence and spread of antibiotic resistance in pathogenic bacteria from farm animals, including farmed fish. This is achieved by monitoring and documenting antibiotic resistance in farm animal pathogens, by activities that increase knowledge of antibiotic resistance and prudent use of antibiotics, and by communication of knowledge to practitioners and farmers. Respiratory pathogens from farm animals are generally susceptible to benzylpenicillin, but penicillin resistance occurs in *Pasteurella multocida* and *Mannheimia haemolytica* from calves and in *Mannheimia haemolytica* and *Bibersteinia trehalosi* from sheep. Resistance is particularly common in *Escherichia coli* isolates from pigs with diarrhoea. Even if most isolates of farm animal pathogens are susceptible to first line antibiotics, susceptibility testing is warranted for guidance in antibiotic therapy as well as monitoring of resistance trends. 

### Selected studies within SvarmPat  
Some of the results regarding resistance in various pathogens are available under the heading Clinical isolates from animals. 

#### Respiratory tract samples from pigs 
Since 2023, clinical respiratory samples from pigs that are PCR-positive for *Actinobacillus pleuropneumoniae*, *Glaesserella parasuis* and *Pasteurella multocida* are being cultured to obtain isolates for susceptibility testing. Resistance to penicillin in these bacteria is uncommon, supporting the recommendation to primarily use penicillin for treatment of pneumonia in pigs.  

#### Respiratory pathogens from pigs at slaughter 
In the autumn of 2024, a project investigated respiratory pathogens and their antibiotic susceptibility in pigs, focusing on whether slaughterhouse sampling could improve surveillance of *Actinobacillus pleuropneumoniae* (APP) and *Pasteurella multocida* [@kyhlsgard2025slaughter]. Samples from 69 lungs with pneumonia or pericarditis and from 19 herds were collected at a slaughterhouse in southern Sweden. One or more pathogens were detected by PCR in 44 samples, most commonly APP (n=33), *P. multocida* (n=15) and *Mycoplasma hyopneumoniae* (n=12). APP and *P. multocida* were also cultured and susceptibility tested. All isolates were susceptible to penicillin. The study shows that slaughterhouse sampling is a possible tool for identifying pathogens and monitoring antibiotic resistance in pig respiratory pathogens. 

#### Enteric samples from pigs 
Resistance to ampicillin, tetracycline and trimethoprim-sulphamethoxazole are the most common resistance traits in *Escherichia coli* isolated from piglets with diarrhoea, and multidrug resistance has varied between 11% and 20% in the last five years. This emphasises the importance of susceptibility testing in herds with neonatal and post-weaning diarrhoea.  

Swine dysentery caused by *Brachyspira hyodysenteriae* is a severe disease in pigs, with a few affected herds each year in Sweden. The resistance situation in the causative agent *B. hyodysenteriae* is favourable compared to many other countries, but clinical resistance to tiamulin in *B. hyodysenteriae* was detected for the first time 2016 in an outbreak in several herds. Within SvarmPat, whole genome sequencing (WGS) confirmed that the outbreak was caused by the same clone [@backhans2020svindysenteri]. After successful eradication in affected herds, no isolates with tiamulin MICs >2 mg/L have been detected since 2018. 

Spirochaetal diarrhoea caused by *Brachyspira pilosicoli* is a less severe but more common disease than swine dysentery. Cases of treatment failure have been reported and multiresistant isolates have been detected, but breakpoints for antibiotic resistance specific for *B. pilosicoli* are lacking.  

#### Neomycin resistance in *Escherichia coli* from pigs with post-weaning diarrhoea 
The sales of neomycin for group treatments of pigs have increased substantially since the 2022 withdrawal of zinc oxide products used to prevent post-weaning diarrhoea (PWD). To compare resistance levels of *E. coli* in farms that do and do not apply group treatments for PWD, a study was conducted in 2025 where samples from up to four pigs with diarrhoea per farm were collected together with information about antibiotic treatments, vaccinations and herd data [@werinder2026neomycin]. Of the 93 tested *E. coli* isolates, 10% were resistant to neomycin and 20% to trimethoprim-sulphamethoxazole, the most common substances used for group and individual treatments, respectively, for PWD. All neomycin resistant isolates came from farms that had used neomycin for group treatments in recent years and the proportion of neomycin resistant isolates from these herds was 16%. The study continues in 2026. 

#### Bacteriological Investigations of suspected new neonatal porcine diarrhoea (NNPD) cases in Sweden 
New neonatal porcine diarrhoea (NNPD) is a serious disease of newborn piglets, in Swedish pig herds often associated with *Enterococcus hirae*. In a study, the presence of *E. hirae* and enterotoxigenic *Escherichia coli* (ETEC) was examined in diarrhoeic piglets less than one week old [@arosenius2025NNPD]. Samples from 67 piglets across 14 herds detected *E. hirae* in all herds and in 53 piglets, while ETEC was found in nine piglets from eight herds. Both bacteria co-occurred in seven cases. In 17 piglets, histological findings revealed enteritis and in four piglets enteroadherent coccoid bacteria. *Enterococcus hirae* was the most common pathogen, but its role is hard to confirm and other contributing factors must be considered. 

#### Antibiotic susceptibility of *Enterococcus hirae* from piglets with new neonatal porcine diarrhoea (NNPD) 
In herds with NNPD penicillin and tylosin are often used, with varying success. *Enterococcus hirae* isolated from 48 piglets with diarrhoea from the NNPD project, was antibiotic susceptibility tested [@rincongracia2026hirae]. The isolates showed varying susceptibility: 40% and 31% were resistant to penicillin and ampicillin, respectively, as well as 21% to tylosin (interpreted with ECOFFS for *E. faecium* and *E. faecalis*). Some isolates showed resistance to all three antibiotics. Surprisingly, a few isolates were susceptible to ceftiofur and had very low penicillin and ampicillin MICs. Sequencing revealed that these isolates that were highly susceptible to beta-lactams differed in one amino acid located in the active site of penicillin-binding protein 5 (PBP5). In conclusion, resistance to antibiotics used to treat NNPD is common among *E. hirae* isolates, and regular monitoring of treatment outcomes is needed. 

#### Respiratory tract samples from calves 
One of the most common infections in calves is pneumonia caused by *Pasteurella multocida*, for which penicillin is considered the first-line antibiotic in Sweden. However, since beta-lactamase producing *P. multocida* have been isolated every year since 2016, sampling and susceptibility testing is important, especially if therapeutic failure is observed in a herd. Since 2023, clinical respiratory samples from calves that are PCR-positive for *P. multocida*, *Mannheimia haemolytica* or *Histophilus somni* are cultured to obtain isolates for susceptibility testing. Also, samples from calves PCR-positive for *Mycoplasma bovis* are cultured and susceptibility tested. MICs for *M. bovis* were high for most antibiotics available for treatment, except for enrofloxacin, and the results indicate that the treatment options for infections with *M. bovis* are few [@backhans2023mycoplasmabovis]. 

#### Survey on antibiotic use for pneumonia caused by *Mycoplasma bovis* 
*Mycoplasma bovis* infections in cattle have increased in Sweden, primarily affecting calves. A 2024 survey of 62 Swedish cattle veterinarians explored antibiotic use in treating respiratory infections, especially those caused by *M. bovis* [@Kuusela2025mycoplasmabovis]. Benzylpenicillin was the first-line treatment for general bovine respiratory disease (97%), often combined with NSAIDs (98%). For suspected *M. bovis*, tetracycline was the most chosen antibiotic (67%), followed by penicillin and florfenicol. Antibiotic choice was mainly guided by national or institutional guidelines. While 35% had treated confirmed or suspected *M. bovis* cases, many (18%) were unsure if they had. Although only 39% routinely used diagnostic sampling, two-thirds reported using it at treatment failure or herd investigations. The study highlights a need for clearer guidelines on when *M. bovis* should be suspected. 

#### Ct-values a tool for quantification of respiratory pathogens? 
In this project, the clinical relevance of real-time PCR Ct (cycle threshold) values was studied by comparing the Ct values, i.e. DNA quantities, of *Pasteurella multocida*, *Histophilus somni* and *Mannheimia haemolytica* between nasal swabs from healthy (n=100) and diseased (n=202) calves [@solvang2026kalv]. Also, the detection rates of respiratory pathogens, detected by real-time PCR for four bacterial species (*Pasteurella multocida*, *Histophilus somni* , *Mannheimia haemolytica* and *Mycoplasma bovis*) and four viral pathogens (bovine coronavirus (BCoV), bovine respiratory syncytial virus (BRSV), and parainfluenza-3 virus (PIV-3)) in nasal swabs from diseased calves and healthy calves were compared. The aim was to identify associations between specific pathogens and clinical illness. Only BRSV was significantly associated with respiratory symptoms, which confirms the importance of infection control. The study found no evidence that conclusions about clinical status can be drawn from Ct values of bacterial findings from nasal swabs. 

#### Milk samples from dairy cows 
Continuous monitoring of resistance in bacteria from clinical mastitis in dairy cows started in 2013. Randomly collected milk samples from dairy cows with clinical mastitis are cultured, isolated bacteria are susceptibility tested and information about the cow and the herd is registered.  

Most pathogens are susceptible to antibiotics used in Sweden and resistance to penicillin in *S. aureus* is low. 

Screening for MRSA in milk samples from dairy cows has been ongoing since 2010 within the SvarmPat programme. Isolates of beta-lactamase producing *S. aureus* from routine submissions to SVA are investigated for methicillin resistance. Between 2013 and 2025, 1553 isolates of anonymous origin have been tested within the screening programme. Ten isolates have been confirmed as MRSA, most recently in 2017. 

#### Viruses likely of minor importance in pneumonia in sheep 
Pneumonia in sheep is a common and multifactorial disease involving commensal bacteria of the upper airways. Knowledge concerning the role of viruses is limited and they are currently not included in the multiplex PCR diagnostics used for respiratory samples at SVA. In 2024, 92 lung samples from sheep with pneumonia were analysed for parainfluensa virus (bovine and caprine/ovine PIV-3), respiratory syncytial virus (RSV: both bovine and ovine) and adenovirus [@seligsohn2026luft]. All samples were negative for PIV-3 and RSV, and four samples that were positive for adenovirus were further characterized by WGS. One sample was identified as ovine mastadenovirus A, while the other three were not possible to characterise further. Altogether, the findings indicate that common respiratory viruses play a limited role in the development of pneumonia in sheep. 

:::
