---
format:
  html:
    embed-resources: false
    toc: false
---


# Contributors and participants {.unnumbered}

### Editors

Hanna Billström, Jennifer Jagdmann and Ragda Obeid - Public Health Agency of Sweden

Oskar Nilsson, Märit Pringle and Krista Tuominen - Swedish Veterinary Agency 

### Data Visualization & Technical Integration Editors

Maximilian Julius Lautenbach - Public Health Agency of Sweden 

Krista Tuominen - Swedish Veterinary Agency 


::::: grid
::: g-col-6

### Authors Swedres

#### Public Health Agency of Sweden

Anette Hulth, Barbro Mäkitalo, Caroline Kaipe, Eva Morfeldt, Hanna Billström, Jessica Darenberg, Jennifer Jagdmann, Jerker Jonsson, Nadja Karamehmedovic, Nasanin Hashemi, Maximilian Julius Lautenbach, Ragda Obeid, Saga Alvring, Sofia Linnros, Sofia Ny, Thomas Åkerlund, Tomas Söderblom, Vilhelm Müller

#### Department of Clinical Microbiology, Karolinska University Hospital 

Karin Haij Bhattarai and Nora Vestberg 

#### Department of Clinical Microbiology, Umeå University Hospital 

Kerstin Granlund 

#### Clinical Microbiology and Infection Control, Region Skåne Office for Medical Services 

Ylva Lindroth 

#### National Reference Laboratory for Fungi, Karolinska University Hospital  

Karin Amilon and Silvia Botero-Kleiven  

#### National Reference Laboratory for Sexually Transmitted Infections & National Reference Laboratory for *Neisseria meningitidis* 

Magnus Unemo and Susanne Jacobsson 

:::

::: g-col-6

### Authors Svarm

#### Swedish Veterinary Agency

Annette Backhans, Anna Bergström, Christina Greko, Annica Landén, Mattias Myrenås, Oskar Nilsson, Märit Pringle, Krista Tuominen and Anna Werinder

### Other contributors in Svarm

#### Swedish Veterinary Agency

Boel Harbom, Natalia Amaya, Charlotta Fasth, Elisabeth Bagge, and Paulina Hysing  

#### Farm & Animal Health

Frida Matti 
:::
:::::


### Acknowledgements

#### Contributions to Swedres

Data was analysed in collaboration with: Anders Ternhag, Annika Hahlin, Elin Dahlén, Inga Fröding and Stephan Stenmark. We are grateful to the National Board of Health and Welfare that provided data on proportions of the population and children treated with at least one course of antibiotics in 2025 and the Medical Products Agency that provided data on adverse drug reactions. The national surveillance of antibiotic resistance would not have been possible without the contribution of data and active support of all the Swedish clinical microbiology laboratories. Epidemiological information on clinical notifications was checked and updated by the Regional Departments for Communicable Disease Control. 

#### Contributions to Svarm

The environmental departments in several municipalities as well as personnel at border control posts are acknowledged and thanked for collecting samples of fresh meat. Personnel at the eHealth Agency are acknowledged for dedicated work on quality of data collected from Swedish pharmacies. 
