---
format:
  html:
    embed-resources: false
    toc: false
---
```{r}
#| results: "asis"
#| echo: false
#| warning: false
#| message: false
source("../_common.R")
status(type = "ready2publish")
```

# Preface {.unnumbered}

The reporting of sales of antibiotics and occurrence of antibiotic resistance in Sweden now moves into a new digital era. This development comes after twenty-five printed reports from the veterinary programme Svarm, of which thirteen have been published together with the human counterpart Swedres. Naturally, there is some sadness in no longer experiencing the satisfaction of unboxing and flicking through a newly published physical report. However, this new way of reporting data opens up possibilities for presenting data in new and interactive ways which outweigh the disadvantages. We are not quite finished yet, but we intend to continue to develop the new digital Swedres-Svarm in the coming years. We hope that you will join us on the journey! While the format is changing, the core purpose of Swedres-Svarm remains the same: to monitor and communicate trends in antibiotic consumption and antimicrobial resistance in Sweden. 

In humans, one important finding is that ESBL~CARBA~ producing bacteria, previously associated primarily with healthcare settings, are now being detected in individuals in Sweden with no prior healthcare exposure. Since 2020, cefotaxime-resistant *E. coli* (ESBL) and methicillin-resistant *S. aureus* (MRSA) in blood are used as antibiotic resistance indicators. Both are slowly rising, reaching 9.0% and 2.4%, respectively. However, the continued decrease in antibiotic sales to humans in Sweden is promising and showcases the successes of sustained hard work.  

On the veterinary side, the spotlight ten to fifteen years ago was on ESBL-producing bacteria among broilers. However, with dedication from the industry in collaboration with the authorities, the occurrence is now low in all investigated animal species. Today, the spotlight is instead mainly on the pig industry. This is due to both the increased need to treat post-weaning diarrhoea and the detection of MRSA in Swedish pig production. Hopefully, with joint efforts, these challenges can also be handled successfully. 


Finally, a new national strategy against antimicrobial resistance was adopted by the Swedish government in November 2025. The work to develop an action plan to achieve the goals set out in the strategy has started and will be finalised in 2026. Hence, the efforts to promote responsible use of antibiotics and counteract selection and spread of resistant bacteria among humans and animals in Sweden continue. 


Solna and Uppsala, June 2026

::: {.grid}  
::: {.g-col-8}
**Johanna Sandwall**

Director General

Swedish Veterinary Agency
:::

::: {.grid}
::: {.g-col-12}
**Olivia Wigzell**

Director General

Public Health Agency of Sweden
:::
