---
format:
  html:
    embed-resources: false
    toc: true
    #toc-depth: 5
    toc-expand: true
execute:
  cache: false
  echo: false
  warnings: false
  error: false
---

```{r}
#| results: "asis"
#| echo: false
#| warning: false
#| message: false
source("../../_common.R")
status(type = "drafting")
```


## Linegraph


```{r}
#| message: false
#| warning: false
data <- load_from_excel(path_file = "data/Figure_ny_Indicators.xlsx")

df <- data$fig_data |>  
 # mutate(across(everything(), as.character)) |>
    rename(antibiotic = Antibiotic) |> 
  pivot_longer(cols = -antibiotic, names_to = "year", values_to = "r_perc")
```
::: panel-tabset
###### Figure
```{r}
##| label: fig-ny-indicators
#| fig-cap: !expr glue::glue("{data$fig_cap}")
#| fig-alt: !expr glue::glue("{data$fig_alt}")
#| warning: false

p <- df |>
  mutate(data_id = row_number(),
         tooltip_l = glue::glue('{antibiotic}'),
         tooltip_p  = glue::glue('<b>Year:</b> {year}
                                   <b>Antibiotic:</b> {antibiotic}
                                   <b>Resistance:</b> {round(r_perc,2)} % resistance')) |>
  ggplot(aes(x= year,
             y=r_perc,
             color = antibiotic,
             data_id = antibiotic)
  ) +
  geom_line_interactive(aes(group=antibiotic, tooltip=tooltip_l),
                        lwd=0.5) +
  geom_point_interactive(aes(tooltip = tooltip_p),
                         #size=.5,
                         hover_nearest = TRUE) +

  scale_x_discrete(expand = c(0,0.2)) +
    scale_y_continuous(breaks = scales::pretty_breaks()) +
   # guides(color=guide_legend(nrow=2)) +

  labs(y="Percentage resistance (%)") +
  scale_color_SweSva() +
  theme_SweSva() +
  add_fohm_caption() +
#      theme(plot.subtitle = element_text(vjust = -15)) +
  theme_SweSva_rotate()

make_dynamic_plot(plot = p, 
                  filename = "fig-ny-indicators")
```
###### Data
```{r}
df |> 
  make_table_data_tab(file_name = "fig-ny-indicators")
```
:::



## Line with CI

```{r}
#| message: false
#| warning: false
data <- load_from_excel(path_file = "data/Figure_3.12_25.xlsx")

df <- data$fig_data |>  
  head(n=6) |> 
  dplyr::select(1:`2025 - % R`) |> 
  mutate(across(everything(), as.character)) |>
    rename(antibiotic = Antibiotic) |> 

  pivot_longer(cols = -antibiotic, names_to = "year_tmp") |> 
  separate(year_tmp, into = c("year","feat"),sep = "-") |> 
  mutate(feat = str_remove(feat,"\r\n")) |> 
  mutate(value = as.numeric(value)) |> 
  pivot_wider(names_from = feat, values_from = value) |> 
    janitor::clean_names() |> 

## confidence interval
  rename(r_perc = percent_r,
         tot_antal = n_tested) |> 
  mutate(r_antal = round(tot_antal*(r_perc/100),0)) |> 
  group_by(antibiotic, year) %>%
  na.omit() |> 
  get_wilson_ci()
```

::: panel-tabset
###### Figure
```{r}
##| label: fig-3-12
#| fig-cap: !expr glue::glue("{data$fig_cap}")
#| fig-alt: !expr glue::glue("{data$fig_alt}")
#| warning: false

p <- df |>
  mutate(data_id=row_number(),
         tooltip_p = glue::glue('{year}<br>{antibiotic}
                                {r_perc}% resistance
                                Confidence interval: {ci}'
                                ),
         tooltip_l = glue::glue('{antibiotic}')) |> 
  ggplot(aes(x= year,
             y=r_perc,
             color = antibiotic,
             data_id = antibiotic)
  ) +
  geom_line_interactive(aes(group=antibiotic, tooltip=tooltip_l),
                        lwd=0.5) +
  geom_point_interactive(aes(tooltip = tooltip_p),hover_nearest = TRUE) +
  geom_errorbar_interactive(aes(ymin = r_perc - felstapel_low,
                                ymax = r_perc + felstapel_high,
                                tooltip = tooltip_p), 
                            width=.15,linewidth = .5
  ) +
  scale_x_discrete(expand = c(0,0.2)) +
    scale_y_continuous(breaks = scales::pretty_breaks(), 
                       limits = c(0,40)) +
  guides(color=guide_legend(nrow=2)) +

  labs(y="Percentage resistance (%)") +
  scale_color_SweSva() +
  theme_SweSva() +
    theme(plot.subtitle = element_text(vjust = -15)) +

  add_fohm_caption()


make_dynamic_plot(plot = p, 
                  filename = "fig-3-12")
```
###### Data
```{r}
df |> 
  make_table_data_tab(file_name = "fig-3-12")
```
:::

## Barplot

::: panel-tabset
```{r}
#| message: false
#| warning: false
data <- load_from_excel(path_file = "data/Figure_3.1_number_resported_cases.xlsx")
df <- data$fig_data |> 
  pivot_longer(cols = -year, names_to = "feature")
```

###### Figure
```{r}
##| label: fig-3-1
#| fig-cap: !expr glue::glue("{data$fig_cap}")
#| fig-alt: !expr glue::glue("{data$fig_alt}")
#| warning: false
p <- df |> 
   mutate(data_id = row_number(),
          tooltip_b = glue::glue('<b>Year:</b> {year}
                                    <b>Notifiable resistance:</b> {feature}
                                    <b>Number of cases:</b> {round(value,0)}')) |> 

  ggplot(aes(y = value,
             x = feature, 
             fill=as.factor(year),
             data_id = data_id)) +
  geom_col_interactive(aes(tooltip = tooltip_b),width = 0.5, position = position_dodge(0.7)) +
  #geom_bar_interactive(aes(tooltip = tooltip_b, width = .8),
  #         position="dodge", stat="identity") +
  labs(x=NULL,
       y = "Number of cases") +
      scale_y_continuous(expand = c(0,0),limits=c(0,round(max(df$value)*1.2,-2))) +
#theme(axis.text.y = element_text(hjust=0))+
#  scale_y_continuous(expand=c(0,.1)) +
  #scale_fill_fohm() +
  scale_fill_SweSva() + 
  theme_SweSva() +
  #theme(axis.text.y = element_text(hjust=1)) +
  add_fohm_caption() 


make_dynamic_plot(plot = p, filename = "Fig3-1")
```
###### Data
```{r}
df |> 
  rename("Notifiable resistance" = feature,
         "Number of cases" = value) |> 
  make_table_data_tab(file_name = "Fig3-1")
```
:::

## table

```{r}
#| message: false
#| warning: false
data <- load_from_excel(path_file = "data/Table_3.5_Kpn.xlsx")

df <- data$fig_data |> 
  mutate(across(c(2:3), as.numeric))
```

::: panel-tabset
###### Table
```{r}
##| label: tbl-3-5
#| tbl-cap: !expr glue::glue("{data$fig_cap}")
df |> 
  gt()|> 
 gt_theme_SweSva()
```

###### Data
```{r}
df |> 
  make_table_data_tab(file_name = "Table3-5")
```
:::











